### ISSUE TITLE
Version 1.0.7 npm install sharedb-ace installs empty folder

### ISSUE THREAD

**Issue by ccyccyccy** [jethrokuan/sharedb-ace#13]
After doing npm install, sharedb-ace folder within node_modules only contains README and package.json with nothing else.

**Comment by jethrokuan** [comment]
spent some time trying to figure it out, but haven't. Don't have time now, feel free to PR.

**Comment by jethrokuan** [comment]
should be fixed in 1.0.9

**Comment by ccyccyccy** [comment]
thanks a lot!
