### ISSUE TITLE
server side example with express

### ISSUE THREAD

**Issue by nareshv** [jethrokuan/sharedb-ace#6]
Thanks for the code !

Can you give an example of how the server side looks with express.js & mysql ?

**Comment by jethrokuan** [comment]
Hi @nareshv,

Unfortunately ShareDB doesn't support mysql. If you're fine with postgresql, then you could use [sharedb-postgres](https://github.com/share/sharedb-postgres).

This is as client-side only project, so no server code was included. For an example of an express server, you can take a look at [server.js](https://github.com/share/sharedb/blob/master/examples/textarea/server.js).

This package is still under heavy development, but I'd probably create a example usage repo later on when things have settled.

**Comment by nareshv** [comment]
cool, thanks !
